// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1djpTZiilzB8AOziltyMPi_NMSQHzRTQ',
    appId: '1:929140423166:web:15eac5032c3c368a8aa8af',
    messagingSenderId: '929140423166',
    projectId: 'tdc-app-ae6c8',
    authDomain: 'tdc-app-ae6c8.firebaseapp.com',
    storageBucket: 'tdc-app-ae6c8.appspot.com',
    measurementId: 'G-YL9P3JQV9R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPGpISE1ktoRYd5ryE8SO28P3wYn6nRRo',
    appId: '1:929140423166:android:9f31918b9a3240b28aa8af',
    messagingSenderId: '929140423166',
    projectId: 'tdc-app-ae6c8',
    storageBucket: 'tdc-app-ae6c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgmBjjXOOPiJiI7UlNRboKzDmBhm2fn34',
    appId: '1:929140423166:ios:c398edb58a6f8a238aa8af',
    messagingSenderId: '929140423166',
    projectId: 'tdc-app-ae6c8',
    storageBucket: 'tdc-app-ae6c8.appspot.com',
    iosBundleId: 'com.example.tdc',
  );
}
